#配置环境 home
spring:
  profiles: home
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mall-oms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
dubbo:
  application:
    name: mall-oms
  registry:
    #公司环境zookeeper://192.168.1.145:2181
    #自己环境zookeeper://192.168.198.129:2181
    address: zookeeper://192.168.198.129:2181
  protocol:
    name: dubbo
    port: 20840
#  provider:
#    cluster: failfast
#打印sql语句
logging:
  level:
    fun.huanghai.mall.dao: debug

---
#配置公司环境
spring:
  profiles: comp
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/mall-oms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
dubbo:
  application:
    name: mall-oms
  registry:
    #公司环境zookeeper://192.168.1.145:2181
    #自己环境zookeeper://192.168.198.129:2181
    address: zookeeper://192.168.1.145:2181
  protocol:
    name: dubbo
    port: 20840
#  provider:
#    cluster: failfast
#打印sql语句
logging:
  level:
    fun.huanghai.mall.dao: debug